### ISSUE TITLE
when tests fail or "oops"

### ISSUE THREAD

**Issue by paulathevalley** [Gastove/formidable-blabs#8]
![test fail](https://cloud.githubusercontent.com/assets/768965/10530589/02b890ce-735e-11e5-9f74-cd733b39f7a9.gif)

**Comment by paulathevalley** [comment]
![oops](https://cloud.githubusercontent.com/assets/768965/10530605/31ef89b0-735e-11e5-9a78-f595b1516f53.gif)

**Comment by karawoo** [comment]
![oh-god-what-have-i-done-panda](https://cloud.githubusercontent.com/assets/4452678/10530644/9dbd25da-735e-11e5-9520-6beef4e46045.gif)
